name: happylocate_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_native_splash: ^2.1.6
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  injectable: ^1.5.3
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  injectable_generator: ^1.5.4

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android_12:
    image: assets/splash.png
    color: "#ffffff"
  #android: false
  #ios: false
  #web: false
flutter:
  uses-material-design: true
  assets:
    - assets/empty_state.png  
